import type { Metadata } from "next";
// eslint-disable-next-line camelcase
import {
  Inter,
  // eslint-disable-next-line camelcase
  Big_Shoulders_Display,
} from "next/font/google";
import "./globals.css";
import React from "react";

const inter = Inter({ subsets: ["latin"] });
const pollyGlot = Big_Shoulders_Display({
  subsets: ["latin"],
  weight: ["700"],
});

export const metadata: Metadata = {
  title: "PolyGlot",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${pollyGlot.className} ${inter.className} `}>
        {children}
      </body>
    </html>
  );
}

export { inter, pollyGlot };
